### ISSUE TITLE
#Feat: Stylization of buttons and links

### ISSUE THREAD

**Issue by mauricioromagnollo** [x0n4d0/proffy#9]
### - Remove the click outline:
```css
.page-header .top-bar-container a {
  outline: none;
}
.page-header .top-bar-container a {
  background: color....;
}
```
### - Add a shadow effect when the button is clicked, giving depth effect
Example:
```css
button {
  box-shadow: 2px 4px #000;
}
button:active {
   box-shadow: none;
}
```
